### ISSUE TITLE
Exit status 128 in log

### ISSUE THREAD

**Issue by f1yegor** [shurcooL/git-branches#1]
$git-branches                                                                                                                                                         error running [git rev-list --count --left-right master...feature/reporting]: exit status 128

**Comment by dmitshur** [comment]
1. What's your version of `git`?
2. Is that the entire output of `git-branches`, or was there more?
3. Do you have `master` branch in your repository?
4. What's the output of `git branch` in that repository?

**Comment by f1yegor** [comment]
1. ➜  ~ git version                                                                                                                         git version 2.5.5
2. ➜  api git:(feature/reporting) ✗ git-branches                                                                                            2016/06/01 20:12:59 error running [git rev-list --count --left-right master...feature/reporting]: exit status 128
   2016/06/01 20:12:59 error running [git rev-list --count --left-right master...develop]: exit status 128
   2016/06/01 20:12:59 error running [git rev-list --count --left-right master...feature/spark-1.6]: exit status 128
   
   ```
   | Branch                | Base   | Behind | Ahead |
   |-----------------------|--------|-------:|:------|
   | **feature/reporting** | master |      ? | ?     |
   | develop               | master |      ? | ?     |
   | feature/spark-1.6     | master |      ? | ?     |
   ```
3. no master 
4. api git:(feature/reporting) ✗ git branch  
   develop
   - feature/reporting
     feature/spark-1.6
     ...several more

**Comment by dmitshur** [comment]
> no master

Gotcha. What do you consider the default branch for that git repo? You should specify that as the base of comparison. If it's "develop", then run:

```
git-branches -base=develop
```

In general, it's not possible to figure out what the default branch of a git repo is, because it may have multiple remotes, and you can't know which is the canonical one.

So `git-branches` just assumes it's master, unless you set it to something else via `-base` flag. Read more about that flag by running `git-branches -help`.

**Comment by f1yegor** [comment]
Sorry, haven't turn on my mind. You are right. Could you include this in README?)

**Comment by dmitshur** [comment]
> Could you include this in README?

Will do. I'll use this issue to track that. Thanks.

**Comment by dmitshur** [comment]
The readme currently says:

> You can see how branches compare to master base branch locally. It supports -base option if you want to compare against a different base branch.

I think that resolves this task.
